# Generated by Django 3.0 on 2020-04-25 15:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contents',
            field=ckeditor.fields.RichTextField(default=True),
            preserve_default=False,
        ),
    ]
