# Generated by Django 3.0 on 2020-04-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200407_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
